set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g status-style 'bg=#282c34 fg=#61afef'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
