git:
  paging:
    colorArg: always
    pager: delta --light --paging=never
gui:
  authorColors:
    "*": default
  theme:
    activeBorderColor:
      - "#824d5b"
      - "bold"
    inactiveBorderColor:
      - "#aab0ad"
    searchingActiveBorderColor:
      - "#824d5b"
      - "bold"
    optionsTextColor:
      - "#2848a9"
    selectedLineBgColor:
      - "#e7d2be"
    cherryPickedCommitFgColor:
      - "#2848a9"
    cherryPickedCommitBgColor:
      - "#6e33ce"
    markedBaseCommitFgColor:
      - "#2848a9"
    markedBaseCommitBgColor:
      - "#AC5402"
    unstagedChangesColor:
      - "#a5222f"
    defaultFgColor:
      - "#3d2b5a"
